// Generates the token CSS and the TypeScript data files from design/*.json.
// design/tokens.json, icons.json and nodes.json are copies of the RNC V2.1 design system's files.
// Run with `npm run generate` after updating them; `npm run build` runs it first.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => JSON.parse(readFileSync(join(root, p), 'utf8'));
const write = (p, s) => { mkdirSync(dirname(join(root, p)), { recursive: true }); writeFileSync(join(root, p), s); };

const tokens = read('design/tokens.json');
const icons = read('design/icons.json');
const nodes = read('design/nodes.json');

// Only the chosen direction ships: Flagship Navy, Newsreader, DM Sans, DM Mono.
const THEME = 'flagship';
const colorOf = (t) => (typeof t.value === 'string' ? t.value : t.value[THEME]);
const colors = Object.fromEntries(tokens.color.tokens.map((t) => [t.name, colorOf(t)]));
const list = (fam) => Object.fromEntries(tokens[fam].tokens.map((t) => [t.name, typeof t.value === 'string' ? t.value : t.value[THEME]]));
const space = list('spacing');
const radius = list('radius');
const shadow = list('shadow');
const fam = tokens.type.families;
const fonts = { display: fam['display-b'], sans: fam.sans, mono: fam.mono };

// Type styles. Serif is for h1 and h2 only, so h3 is set in DM Sans (as the concepts set card titles).
const group = (prefix) => tokens.type.groups.find((g) => g.name.startsWith(prefix));
const styles = [];
for (const s of group('Pairing B').styles) {
  const name = s.name.replace(/^b-/, '');
  if (name === 'h3') styles.push({ name, family: 'sans', fontSize: '21px', lineHeight: 1.25, fontWeight: 600, letterSpacing: '-0.005em' });
  else styles.push({ ...s, name, family: 'display' });
}
for (const s of group('Text').styles) styles.push({ ...s, family: 'sans' });
for (const s of group('Figures ·').styles) styles.push({ ...s, family: 'mono' });

const px = (v) => (typeof v === 'number' ? v + 'px' : v);
let css = `/* @rafflenexuscanada/design-system tokens (generated from design/tokens.json; do not edit by hand).
   Flagship Navy, Newsreader headlines, DM Sans text, DM Mono figures. */
:root {
`;
for (const [k, v] of Object.entries(colors)) css += `  --${k}: ${v};\n`;
for (const [k, v] of Object.entries(shadow)) css += `  --${k}: ${v};\n`;
for (const [k, v] of Object.entries(space)) css += `  --${k}: ${px(v)};\n`;
for (const [k, v] of Object.entries(radius)) css += `  --${k}: ${px(v)};\n`;
css += `  --font-display: ${fonts.display};\n  --font-sans: ${fonts.sans};\n  --font-mono: ${fonts.mono};\n}\n\n`;
css += `/* Type styles: add the class, e.g. <h2 className="rnc-h2">. */\n`;
for (const s of styles) {
  css += `.rnc-${s.name} { font-family: var(--font-${s.family}); font-size: ${px(s.fontSize)}; line-height: ${s.lineHeight}; font-weight: ${s.fontWeight};`;
  if (s.letterSpacing) css += ` letter-spacing: ${s.letterSpacing};`;
  if (s.opticalSize) css += ` font-variation-settings: 'opsz' ${s.opticalSize};`;
  if (s.family === 'mono') css += ' font-variant-numeric: tabular-nums;';
  if (s.family === 'display') css += ' text-wrap: balance;';
  css += ' }\n';
}
write('styles/tokens.css', css);

const banner = '// Generated by scripts/generate.mjs from design/*.json. Do not edit by hand.\n';
write('src/generated/tokens.ts', banner +
  `export const tokens = ${JSON.stringify({ color: colors, space, radius, shadow, font: fonts }, null, 2)} as const;\n\n` +
  `export type ColorToken = keyof typeof tokens.color;\n`);
write('src/generated/icons.ts', banner +
  '/** Phosphor Icons, regular weight (MIT licence). Paths for a 256 × 256 viewBox. */\n' +
  `export type IconName = ${Object.keys(icons).map((k) => JSON.stringify(k)).join(' | ')};\n\n` +
  `export const ICONS: Record<IconName, string> = ${JSON.stringify(icons, null, 1)};\n\nexport const ICON_NAMES = Object.keys(ICONS) as IconName[];\n`);
write('src/generated/nodes.ts', banner +
  "/** The Raffle Nexus logo's node shapes, traced from the brand files. [viewBox, path]. */\n" +
  `export type NodeName = ${Object.keys(nodes).map((k) => JSON.stringify(k)).join(' | ')};\n\n` +
  `export const NODES: Record<NodeName, readonly [viewBox: string, path: string]> = ${JSON.stringify(nodes)};\n\nexport const NODE_NAMES = Object.keys(NODES) as NodeName[];\n`);
const b64 = (p) => 'data:image/png;base64,' + readFileSync(join(root, p)).toString('base64');
write('src/generated/marks.ts', banner +
  '/** The Raffle Nexus ticket mark, for PoweredBy. Trademark of Raffle Nexus Canada. */\n' +
  `export const MARK_NAVY = ${JSON.stringify(b64('assets/rnc-mark-navy.png'))};\nexport const MARK_WHITE = ${JSON.stringify(b64('assets/rnc-mark-white.png'))};\n`);
console.log(`generated: ${Object.keys(colors).length} colours, ${styles.length} type styles, ${Object.keys(icons).length} icons, ${Object.keys(nodes).length} node shapes`);
